### ISSUE TITLE
Some files seem missing

### ISSUE THREAD

**Issue by jytime** [DL3DV-10K/Dataset#6]
Hi,

Thanks for sharing this great dataset! I have successfully downloaded 1k-4k. When trying to download 5k-7k, it works for colmap cache while some image+poses files are missing. For example:

```
Downloading:  98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊   | 979/1000 [1:18:30<01:41,  4.81s/it]
Traceback (most recent call last):
  File "/data/home/jianyuan/miniconda3/envs/vggsfm/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 286, in hf_raise_for_status
    response.raise_for_status()
  File "/data/home/jianyuan/miniconda3/envs/vggsfm/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/datasets/DL3DV/DL3DV-ALL-960P/resolve/main/5K/bcb0f8befe19e48eb395f40fdde9a0e8b1d2ed300d951bf041f6ae88fa9410e0.zip


Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋| 998/1000 [1:04:36<00:07,  3.88s/it]
Traceback (most recent call last):
  File "/data/home/jianyuan/miniconda3/envs/vggsfm/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 286, in hf_raise_for_status
    response.raise_for_status()
  File "/data/home/jianyuan/miniconda3/envs/vggsfm/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/datasets/DL3DV/DL3DV-ALL-960P/resolve/main/6K/c6626ee2d9f843422628367e008052e9e0bf52f7c2db041ffa7401c808a9f4a7.zip


Retry 1
Downloading:  99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎ | 989/1000 [1:18:43<00:52,  4.78s/it]
Traceback (most recent call last):
  File "/data/home/jianyuan/miniconda3/envs/vggsfm/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 286, in hf_raise_for_status
    response.raise_for_status()
  File "/data/home/jianyuan/miniconda3/envs/vggsfm/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/datasets/DL3DV/DL3DV-ALL-960P/resolve/main/7K/cb6f596cb5fcfea042bc5cd5ec37baf472cc4600034160eb04029a9d16444999.zip

```

All of them happen at the last few scenes.

**Comment by ShengCN** [comment]
Thanks for reporting this. We are working on fixing this problem soon. @jytime

**Comment by justachetan** [comment]
Hi, is this issue resolved? I tried downloading the 4K subset, but that only led to 1K directories being downloaded. Also, the repository description says that the 7K subset is available for download, but when I try entering 7K as my download option, it throws an error.

**Comment by ShengCN** [comment]
@justachetan @jytime I think this problem has been solved now. Feel free to leave comments for any problems. The download.py script has also been updated. Remember to use the new script.
